name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  GO_VERSION: 1.19.x
  GOLANGCI_LINT_VERSION: v1.49.0
  GO111MODULE: on
  GOPRIVATE: github.com/indochat/*
  GO_MODULES_TOKEN: ${{ secrets.GO_MODULES_TOKEN }}
  
jobs:
  run-go-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: task_list
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go version
        run: |
          go version

      - name: Start mysql service
        run: sudo systemctl start mysql

      - name: Go test
        run: |
          go mod tidy
          make seed-flush
          make test
